### ISSUE TITLE
Eliminate default application/json as content type while doing "fn call"

### ISSUE THREAD

**Issue by denismakogon** [fnproject/cli#253] opened 2018-04-30 18:01 UTC
Original issue: https://github.com/fnproject/fn/issues/964
Related: https://github.com/fnproject/fdk-go/issues/23

**Comment by rikgibson** [comment] 2018-05-02 15:25
@denismakogon see #246 and related sub-issues. On our backlog, let me know if this needs prioritising sooner.

**Comment by denismakogon** [comment] 2018-05-02 15:37
that's something needs to be done soon enough because it harms cloudevents experience at this moment.

**Comment by rikgibson** [comment] 2018-05-04 13:26
OK, will get someone on it.

**Comment by rikgibson** [comment] 2018-05-09 14:06
Closing - duplicate of #246.

**Closed by rikgibson** 2018-05-09 14:06 UTC
