### ISSUE TITLE
RFE: No directory should be created when 'fn init' fails

### ISSUE THREAD

**Issue by delabassee** [fnproject/cli#82] opened 2017-10-25 16:20 UTC
`fn init xxx --runtime yyy` will fails because the 'yyy' runtime doesn't exist but still, an empty 'xxx' dir will be created.

**Comment by AstromechZA** [comment] 2017-12-28 10:42
I'd like to pick this one up.

Reproduced on current master below:

```
$ ~/projects/go_workspace/src/github.com/fnproject/cli/fn init xxx --runtime yyy
Creating function at: /xxx
Runtime: yyy
Init does not support the yyy runtime, you'll have to create your own Dockerfile for this function.
ERROR: could not detect entrypoint or cmd for yyy, use --entrypoint and/or --cmd to set them explicitly
$ ls
xxx/
```

**Comment by AstromechZA** [comment] 2017-12-28 12:13
Fix just needs some review at https://github.com/fnproject/cli/pull/129

**Comment by AstromechZA** [comment] 2017-12-29 07:26
Fix is merged. Just need someone to close this issue since the PR didn't do it.

**Closed** 2017-12-29 07:41 UTC
Labels: good first issue
