### ISSUE TITLE
Config mapping from app.yml file goes into route config instead of an app config

### ISSUE THREAD

**Issue by denismakogon** [fnproject/cli#250] opened 2018-04-26 22:08 UTC
## problem

when you would try to deploy an application using `app.yml` file, the configuration mapping (if present) will not go to an app config but will be merged into a route config.

## steps to reproduce

1. Create `app.yml`:
```yaml
name: test-app
config:
    A: "a"
    B: "b"
```
2. Create a function:
```bash
fn init --runtime go test-function
```
3. Deploy:
```bash
fn deploy --all --registry `whoami`
```
4. Inspect the app:
```json
{
	"created_at": "2018-04-27T00:48:37.639+03:00",
	"name": "test-app",
	"updated_at": "2018-04-27T00:48:37.639+03:00"
}
```
5. Inspect a route:
```json
{
	"config": {
		"A": "a",
		"B": "b"
	},
	"created_at": "2018-04-27T00:48:37.643+03:00",
	"format": "json",
	"idle_timeout": 200,
	"image": "...",
	"memory": 1024,
	"path": "...",
	"timeout": 60,
	"type": "sync",
	"updated_at": "2018-04-27T00:48:37.643+03:00"
}
```

## expected behaviour

If config is present in the app file it should end up in an application config, but not be merged into a route config.

**Comment by carimura** [comment] 2018-04-29 19:40
confirmed, I can reproduce this. Needs fixed ASAP.

**Comment by hibooboo2** [comment] 2018-04-30 14:44
@carimura The design of this was that app config is picked up and reflected in route config. This was not a bug. If we want this changed that can be done but this is supposed to merge app config with route config where any value in app config is overridden by route if they are the same value name but a different value.

**Comment by hibooboo2** [comment] 2018-04-30 15:00
Ok so It looks as if the config values are merged at runtime by fn. I will go ahead and fix the code such that these configs are not merged by cli as the way I did that was incorrect. Thank you for pointing this out.

**Closed** 2018-05-01 23:07 UTC
Labels: bug
