### ISSUE TITLE
Support operating system variables inheriting while testing

### ISSUE THREAD

**Issue by denismakogon** [fnproject/cli#6] opened 2017-08-25 21:25 UTC
So, when developer wants to test function, he uses `test.json` as a test contract
```
{
  "tests": [
    {
      "input": {
        "body": {
          "name": "Johnny"
        }
      },
      "output": {
        "body": {
          "message": "Hello Johnny"
        }
      }
    }
  ]
}
```
This proposal addressing certain cases when secrets needs to be ignored by VCS, for particular instance:
`i want to store my API keys away from Git but want to keep test.json in-tree`

So, proposing one for test contract attribute in addition that what already we have:
 - `from_os` or `from_env` (just need certain name that does not collide with `env` attribute of test.

@treeder @carimura @hibooboo2

**Comment by hibooboo2** [comment] 2017-08-25 21:47
Not sure what you are asking here... or after...

**Comment by treeder** [comment] 2017-08-25 22:18
Sounds like dupe of this: https://github.com/fnproject/fn/issues/129

**Comment by denismakogon** [comment] 2017-08-25 22:48
@treeder it's a not dupe, that ticket says about `fn run`, but having ability to pass operating system env variables to a function while running it with `fn test`.

**Comment by carimura** [comment] 2017-08-26 00:28
Sounds like the exact same functionality intended for `fn run` applied to `fn test`. I like it!

**Closed** 2017-09-29 23:20 UTC
